version: "3"

services:
  redis-master-1:
    image: redis:latest
    container_name: redis-master-1
    network_mode: "host"
    volumes:
      - ./conf/redis-master-1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6379:6379
      - 16379:16379

  redis-master-2:
    image: redis:latest
    container_name: redis-master-2
    network_mode: "host"
    volumes:
      - ./conf/redis-master-2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6380:6380
      - 16380:16380

  redis-master-3:
    image: redis:latest
    container_name: redis-master-3
    network_mode: "host"
    volumes:
      - ./conf/redis-master-3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6381:6381
      - 16381:16381
# docker-compose exec redis-master-1 redis-cli --cluster create 10.10.10.50:6379 10.10.10.50:6380 10.10.10.50:6381
