version: "3"

services:
  redis-cluster:
    # platform: linux/x86_64 # M1 MacOS
    image: redis:latest
    container_name: redis-test
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6380
      - 6381:6381
      - 6379:6379

  redis-node-1:
    network_mode: "service:redis-cluster"
    # platform: linux/x86_64 # M1 MacOS
    image: redis:latest
    container_name: redis-test1
    volumes:
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    network_mode: "service:redis-cluster"
    # platform: linux/x86_64 # M1 MacOS
    image: redis:latest
    container_name: redis-test2
    volumes:
      - ./conf/redis-node2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
    # platform: linux/x86_64 # M1 MacOS
    image: redis:latest
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
