version: '2'
services: 
  postgres:
    image: postgres:10
    container_name: postgres
    environment: 
      - POSTGRES_PASSWORD=P@ssw0rd
    ports: 
      - '15432:5432'
    volumes: 
      - ./postgre-data:/var/lib/postgresql/data
