version: "2"
services:
  postgres:
    image: postgres:10
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
