version: "3"

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./seq-data:/data
    ports:
      - 8090:80
      - 5341:5341
