version: "3.7"

services:
  oracle19c:
    image: oracle/database:19.3.0-ee
    container_name: oracle19c
    environment:
      - ORACLE_SID=oracldev
      - ORACLE_PDB=orclpdb
      - ORACLE_PWD=P@ssw0rd
      - ORACLE_MEM=4000
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./oracle-setup:/opt/oracle/scripts/setup
    ports:
      - "1521:1521"
      - "5500:5500"
    restart: "unless-stopped"
