version: "3.3"

services:
  registry:
    restart: always
    image: registry:latest
    ports:
      - 5000:5000
    volumes:
      - ./images:/var/lib/registry
      - ./auth:/auth
    environment:
      - "REGISTRY_AUTH=htpasswd"
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd"