version: "2"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@shockz.io
      - PGADMIN_DEFAULT_PASSWORD=P@ssw0rd
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/root/.pgadmin
