version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - ./mssql-data:/var/opt/mssql/data
    ports:
      - "11433:1433"
    restart: "unless-stopped"