version: "3"

services:
  mssql-fts:
    # image: ghcr.io/shockzinfinity/mssql-fts:latest
    container_name: mssql-fts
    build:
      context: .
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=True
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - ./mssql-data:/var/opt/mssql/data
    ipc: host
    ports:
      - "11434:1433"
    restart: unless-stopped
