version: "3"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "jenkins_docker"
    restart: always
    user: root
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
