version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./app:/app
  php:
    # image: php:7.4-fpm
    build:
      context: ./php
    volumes:
      - ./app:/app
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      WORDPRESS_DB_HOST: maria
      WORDPRESS_DB_NAME: koreatraveleasy
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: P@ssw0rd
    extra_hosts:
      - "host.docker.internal:host-gateway"

  maria:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "P@ssw0rd"
      MYSQL_DATABASE: "wordpress"
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
